backend:
    name: github
    repo: creativeplus2/schonid
    branch: main
    auth_type: pat # ðŸ‘ˆ penting!

media_folder: 'assets/uploads'
public_folder: '/assets/uploads'

collections:
    - name: products
      label: Products
      folder: '_products'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: Title, name: title, widget: string }
          - { label: Order, name: order, widget: number }
          - { label: Category, name: category, widget: string }
          - { label: Thumbnail, name: thumb, widget: image }
          - { label: Body, name: body, widget: markdown }

    - name: pages
      label: Pages
      files:
          - label: Home
            name: home
            file: index.md
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Body, name: body, widget: markdown }
