backend:
    name: github
    repo: creativeplus2/schonid
    branch: main
    auth_type: pat # ðŸ‘ˆ penting!

media_folder: 'assets/images'
public_folder: '/assets/images'

collections:
    - name: products
      label: Products
      folder: '_products'
      create: true
      nested: true
      slug: '{{title | slugify}}'
      summary: '{{title}} â€” {{category}}'
      fields:
          - { label: Layout, name: layout, widget: hidden, default: product }

          - label: Title
            name: title
            widget: string

          - label: Category
            name: category
            widget: select
            options:
                - workstation
                - desking-storage
                - chairs

          - label: Order
            name: order
            widget: number
            value_type: int
            min: 1

          - label: Banner Image
            name: banner
            widget: image
            media_folder: '/assets/images'

          - label: Thumbnail Image
            name: thumb
            widget: image
            media_folder: '/assets/images'

          - label: Gallery
            name: gallery
            widget: list
            fields:
                - { label: Image, name: src, widget: image }
                - { label: Alt Text, name: alt, widget: string, required: false }

          - label: Content
            name: body
            widget: markdown
    - name: site_config
      label: Site Configuration
      files:
          - name: config
            label: Global Config
            file: '_data/config.yaml'
            fields:
                - label: Address
                  name: address
                  widget: markdown

                - label: Navigation
                  name: nav
                  widget: list
                  fields:
                      - { label: Title, name: title, widget: string }
                      - { label: URL, name: url, widget: string }

                - label: Product Categories
                  name: product_categories
                  widget: list
                  fields:
                      - { label: Key, name: key, widget: string }
                      - { label: Title, name: title, widget: string }
    - name: pages
      label: Pages
      files:
          - label: Home
            name: home
            file: index.md
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Body, name: body, widget: markdown }
